In [1]:
import pandas as pd 
import numpy as np # pip install numpy
s= pd.Series([13,33,21,np.nan,43,22,np.nan,56,78, np.nan])
s

0    13.0
1    33.0
2    21.0
3     NaN
4    43.0
5    22.0
6     NaN
7    56.0
8    78.0
9     NaN
dtype: float64

In [3]:
s.shape

(10,)

In [4]:
s.isnull()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9     True
dtype: bool

In [5]:
s[s.isnull()]

3   NaN
6   NaN
9   NaN
dtype: float64

In [6]:
s.isnull().sum()

3

In [8]:
s.isna().sum()

3

In [9]:
s.isnull().any()

True

In [11]:
s.hasnans

True

In [15]:
s.dropna()  # to drop null values

0    13.0
1    33.0
2    21.0
4    43.0
5    22.0
7    56.0
8    78.0
dtype: float64

In [14]:
s.dropna(ignore_index=True)  # to drop null values

0    13.0
1    33.0
2    21.0
3    43.0
4    22.0
5    56.0
6    78.0
dtype: float64

In [16]:
s.mean()

38.0

In [19]:
s.fillna(s.mean(), inplace=True)

In [20]:
s

0    13.0
1    33.0
2    21.0
3    38.0
4    43.0
5    22.0
6    38.0
7    56.0
8    78.0
9    38.0
dtype: float64

In [21]:
# numpy 
import numpy as np 

In [22]:
arr= np.array([12,145,43,21,100])

In [23]:
arr

array([ 12, 145,  43,  21, 100])

In [24]:
# dimensions
arr.ndim

1

In [25]:
arr2= np.array([[12,10,23,45]])
arr2

array([[12, 10, 23, 45]])

In [26]:
arr2.ndim

2

In [29]:
arr2= np.array([[12,13,14],[89,87,76],[1,2,3]])
arr2

array([[12, 13, 14],
       [89, 87, 76],
       [ 1,  2,  3]])

In [30]:
arr2.ndim

2

In [31]:
arr3= np.array([
    [
        [12,13],
        [23,24]
    ],
    [
        [45,54],
        [22,12]
    ]
])
arr3

array([[[12, 13],
        [23, 24]],

       [[45, 54],
        [22, 12]]])

In [32]:
arr3.ndim

3

In [33]:
arr

array([ 12, 145,  43,  21, 100])

In [34]:
arr.sum()

321

In [36]:
arr3.sum()

205

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
i= np.identity(8)

In [47]:
i

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [42]:
i.ndim

2

In [43]:
i.shape

(8, 8)

In [44]:
i.reshape(16,4)

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [46]:
i.reshape(2,32)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [48]:
arr2

array([[12, 13, 14],
       [89, 87, 76],
       [ 1,  2,  3]])

In [49]:
arr2.reshape(-1)

array([12, 13, 14, 89, 87, 76,  1,  2,  3])

In [50]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b= np.array([
    [11,12,13],
    [23,21,11],
    [22,23,33]
])


In [51]:
a+b

array([[12, 14, 16],
       [27, 26, 17],
       [29, 31, 42]])

In [52]:
b

array([[11, 12, 13],
       [23, 21, 11],
       [22, 23, 33]])

In [53]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
a.sum(axis=0) 

array([12, 15, 18])

In [57]:
a.sum(axis=1)

array([ 6, 15, 24])

In [59]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [64]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])